apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxpassport.fullname" . }}
  labels:
    app: {{ include "oxpassport.name" . }}
    chart: {{ include "oxpassport.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "oxpassport.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "oxpassport.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
        command:
          - /bin/sh
          - -c 
          - |
              /usr/bin/python /scripts/updatelbip.py &
              /app/scripts/entrypoint.sh
        {{- end }}
        ports:
          - name: http
            containerPort: 8090
            protocol: TCP
        envFrom:
          - configMapRef:
              name: {{ include "oxpassport.name" . }}
        volumeMounts:
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
          - name: {{ include "oxpassport.name" . }}-updatelbip
            mountPath: /scripts
        {{- end }}
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-cert
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
        livenessProbe:
          httpGet:
            path: /passport/token
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 20
        readinessProbe:
          httpGet:
            path: /passport/token
            port: http
          initialDelaySeconds: 25
          periodSeconds: 25
          failureThreshold: 20
      volumes:
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
        - name: {{ include "oxpassport.name" . }}-updatelbip
          configMap:
            name: {{ .Release.Name }}-updatelbip
        {{- end }}
        - name: cb-pass
          secret:
            secretName: {{ include "oxpassport.name" . }}-cb-pass
        - name: cb-cert 
          secret: 
            secretName: {{ include "oxpassport.name" . }}-cb-cert 
