apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "opendj.fullname" . }}
  labels:
    app: opendj
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/opendj"
    type: DirectoryOrCreate
  