apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "casa.fullname" . }}
  labels:
      casa: casa 
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  hostPath:
    path: "/etc/gluu/conf"
    type: DirectoryOrCreate