kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "casa.fullname" .}}
spec:
  storageClassName: ""
  volumeName: {{ include "casa.fullname" . }}
  accessModes: 
    - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels: 
      storage: casa 